--TA PARAKATW INSERT EINAI ENDEIKTIKA. H OLOKLHRWMENH EISAGWGH OLWN TWN DEDOMENWN APO TA .CSV ARXEIA EPITYGXANETAI ME TO PYTHON SCRIPT insert_data_1.py

INSERT INTO COUNTRIES VALUES (1,'Afghanistan');

INSERT INTO Vaccine_Companies VALUES (1, 'Pfizer Inc. and BioNTech', 'Pfizer Inc. and BioNTech', 'Pfizer Inc. and BioNTech');

--LOGO KSENOU KLEIDIOU fk_VCto_Countries EINAI APARAITHTO GIA TO INSERT POU THA AKOLOUTHISEI NA EXEI GEMISEI O PINAKAS COUNTRIES H NA YPARXEI TOYLAXISTON TO SUGKEKRIMENO COUNTRY_CODE ALLIWS THA PROKIPSEI SFALMA KSENOY KLEIDIOY
INSERT INTO Population VALUES ('248926ca-429b-5c42-b229-f8f0907f712b', 'IT 17421', 'Ivan', 'Harvey', '11/10/1958', '(475) 230-6841', 'Niwbo Place 365', 61982, 'Vinudew', 'DC', 1);

--LOGO KSENOU KLEIDIOU fk_VCto_Countries EINAI APARAITHTO GIA TO INSERT POU THA AKOLOUTHISEI NA EXEI GEMISEI O PINAKAS COUNTRIES H NA YPARXEI TOYLAXISTON TO SUGKEKRIMENO COUNTRY_CODE ALLIWS THA PROKIPSEI SFALMA KSENOY KLEIDIOY
INSERT INTO Vaccination_Centers VALUES (508, 9974467,'WAGONER COMMUNITY HOSPITAL','1200 WEST CHEROKEE STREET','WAGONER', 'OK', 74467, '(918) 485-5514', 'WAGONER', 1, 35.96152396,	-95.3924305, '	http://www.wagonerhospital.com', 'Y');

--LOGO KSENWN KLEIDIWN fk_Vaccinations_to_Population,fk_Vacc_to_VCO,fk_Vacc_to_VCenters EINAI APARAITHTO GIA TO INSERT POU THA AKOLOUTHISEI NA EXEI GEMISEI O PINAKAS POPULATION,Vaccine_Companies,Vaccination_Centers H NA YPARXOYN TOYLAXISTON OI SUGKEKRIMENES TIMES TOU QUERY STOUS ANTISTOIXOUS PINAKES
INSERT INTO Vaccinations VALUES (109, '248926ca-429b-5c42-b229-f8f0907f712b', 1, 'TRUE', '11-02-2021','FALSE', null, 9974467);


